### ISSUE TITLE
Git integration

### ISSUE THREAD

**Issue by Chrjsen** [Chrjsen/seer#23]
Having Git integration in a code editor is almost 100% necessary in today's world. Every software project in modern times are run using source control management software such as git.
We need git integration at some point in time.
It has a low priority for now, since it is quite the undertaking.

**Comment by 064xp** [comment]
Maybe through the access of the command line within node? So as to execute git commands in the background.

**Comment by Chrjsen** [comment]
Quite possibly. There might be some OS-dependencies between Linux/Windows though? Otherwise it should be possible to do using one of the HTTP node modules bundled with electron (I believe it comes bundled with the installation)
